# Generated by Django 3.2.15 on 2023-07-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='username')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
            ],
        ),
    ]
