# Generated by Django 3.2.15 on 2023-07-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodsBusAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32)),
                ('Length', models.FloatField()),
                ('Median', models.FloatField()),
                ('Mean', models.FloatField()),
                ('Mode', models.FloatField()),
                ('Maximum', models.FloatField()),
                ('Minimum', models.FloatField()),
                ('Variance', models.FloatField()),
                ('Quartile_0_25', models.FloatField()),
                ('Quartile_0_75', models.FloatField()),
                ('Skewness', models.FloatField()),
                ('Kurtosis', models.FloatField()),
            ],
            options={
                'db_table': 'bods_bus_analysis',
                'managed': False,
            },
        ),
    ]
